module:
  mounts:
    - source: archetypes
      target: archetypes
    - source: assets
      target: assets
    - source: content
      target: content
    - source: i18n
      target: i18n
    - source: layouts
      target: layouts
params:
  projects:
    thumbnail:
      desktop: '416x312'
      desktop_large: '636x1071'
      mobile: '300x225'
      scrollsnap: '240x180'

# Default
permalinks:
  projects: /projects/:year-:slug/
